services:
  app:
    build: .
    container_name: lead-enrichment-app
    ports:
      - "3032:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    external: true 
